server:
  port: 8084
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/spring-boot-microservices-realm
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: EXPENSES-SERVICE
          uri: lb://EXPENSES-SERVICE
          predicates:
            - Path=/expenses/**

        - id: USERS-SERVICE
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/users/**

        - id: CONTROL-WALLET-SERVICE
          uri: lb://CONTROL-WALLET-SERVICE
          predicates:
            - Path=/api/wallet/**

        - id: REGISTRY-SERVICE
          uri: http://localhost:8761
          predicates:
                - Path=/eureka/web
          filters:
            - SetPath=/

        - id: REGISTRY-SERVICE-STATIC
          uri: http://localhost:8761
          predicates:
                - Path=/eureka/**



logging:
  level:
    org:
      springframework:cloud:gateway:route:RouteDefinitionLocator: INFO
    root: INFO
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka